In [32]:
import sys
from pathlib import Path
import pandas as pd

# 获取当前 notebook 的路径
notebook_path = Path().resolve()

# 获取项目根目录路径
project_root = notebook_path.parent  # 假设 notebook 在项目的子目录下

BASE = Path().resolve().parent
RAW = BASE / "data" / "original_data"
BLD = BASE /"data" / "processed"
OUTPUT = BASE /"data" / "outputs"

In [33]:
RAW

PosixPath('/Users/hengdegao/python/thesis/data/original_data')

In [67]:
# 定义列和筛选条件
columns = ['Stkcd', 'Reptdt', 'Curtype', 'Isam', 'Repat','Content','Kind']
priority_repat = [ 2, 5, 6, 15]
df_1_path = RAW/"csmar"/"股东治理"/"关联交易情况文件"/"RPT_Operation1.csv"
df_2_path = RAW/"csmar"/"股东治理"/"关联交易情况文件"/"RPT_Operation.csv"


# 文件 1：处理 Isam 无问题的文件
df_chunks1 = pd.read_csv(
    df_1_path,
    usecols=columns,
    dtype={'Stkcd': str, 'Isam': float},  # Isam 直接读取为 float
    chunksize=1000
)

# 文件 2：处理可能有 Isam 类型问题的文件
df_chunks2 = pd.read_csv(
    df_2_path,
    usecols=columns,
    dtype={'Stkcd': str},  # Isam 先读取为默认类型
    chunksize=1000
)

# 合并所有块
combined_chunks = []

# 处理文件 1
for chunk in df_chunks1:
    # 筛选符合条件的数据
    filtered_chunk = chunk[chunk["Repat"].isin(priority_repat)]
    combined_chunks.append(filtered_chunk)

# 处理文件 2
for chunk in df_chunks2:
    # 筛选符合条件的数据
    filtered_chunk = chunk[chunk["Repat"].isin(priority_repat)].copy()
    # 将 Isam 转换为数值类型，非法值处理为 NaN
    filtered_chunk.loc[:, 'Isam'] = pd.to_numeric(filtered_chunk['Isam'], errors='coerce')
    combined_chunks.append(filtered_chunk)

# 合并两个文件的结果
final_df = pd.concat(combined_chunks, ignore_index=True)
final_df['Isam'] = final_df['Isam'].astype(float)


# 查看结果
print(final_df.head())
print(final_df.dtypes)

# 如果需要保存为新的文件

    Stkcd      Reptdt  Repat  Kind Curtype         Isam Content
0  600760  2017-12-31    5.0  拆入资金     CNY   40000000.0    拆入资金
1  600760  2017-12-31    5.0  拆入资金     CNY  100000000.0    拆入资金
2  600760  2017-12-31    5.0  拆出资金     CNY   20000000.0    拆出资金
3  600760  2017-12-31    5.0  拆出资金     CNY   50000000.0    拆出资金
4  600760  2017-12-31    5.0  拆出资金     CNY   50000000.0    拆出资金
Stkcd       object
Reptdt      object
Repat      float64
Kind        object
Curtype     object
Isam       float64
Content     object
dtype: object

In [80]:
columns = ['Stkcd', 'Reptdt', 'Curtype', 'Isam', 'Repat']
priority_repat = [ 2, 5, 6, 15]
df_path = RAW/"csmar"/"股东治理"/"关联交易情况文件"/"RPT_Operation.csv"
df_chunks1 = pd.read_csv(
    df_path,
    usecols=columns,
    dtype={'Stkcd': str, 'Isam': float},  # Isam 直接读取为 float
    chunksize=1000
)
filtered_chunk.loc[:, 'Isam'] = pd.to_numeric(filtered_chunk['Isam'], errors='coerce')
final_df['Isam'] = final_df['Isam'].astype(float)
print(final_df.head())
print(final_df.dtypes)

    Stkcd      Reptdt  Repat  Kind Curtype         Isam Content  \
0  600760  2017-12-31    5.0  拆入资金     CNY   40000000.0    拆入资金
1  600760  2017-12-31    5.0  拆入资金     CNY  100000000.0    拆入资金
2  600760  2017-12-31    5.0  拆出资金     CNY   20000000.0    拆出资金
3  600760  2017-12-31    5.0  拆出资金     CNY   50000000.0    拆出资金
4  600760  2017-12-31    5.0  拆出资金     CNY   50000000.0    拆出资金

   transaction_CNY
0       40000000.0
1      100000000.0
2       20000000.0
3       50000000.0
4       50000000.0
Stkcd               object
Reptdt              object
Repat              float64
Kind                object
Curtype             object
Isam               float64
Content             object
transaction_CNY    float64
dtype: object

In [81]:
final_df['Reptdt'].value_counts()

Reptdt
2022-12-31    84032
2023-12-31    83658
2021-12-31    81357
2020-12-31    76303
2019-12-31    70100
2018-12-31    64664
2017-12-31    60219
2016-12-31    51514
2015-12-31    42787
2014-12-31    36881
Name: count, dtype: int64

In [48]:
final_df['Curtype'].value_counts()

Curtype
CNY     630061
USD       8920
EUR       1644
HKD        563
AUD        188
JPY        168
TWD         94
BRL         82
GBP         54
NZD         51
MYR         39
CAD         31
THB         29
VND         20
IDR         11
SGD         10
INR          9
AED          7
ZAR          6
KRW          4
MXN          4
KWD          4
SEK          4
MOP          4
CZK          3
CHF          3
LAK          3
ILS          3
PLN          3
PKR          3
HUF          3
DKK          2
QAR          2
EGP          1
LKR          1
MNT          1
接受劳务         1
NOK          1
OMR          1
RUB          1
22"          1
Name: count, dtype: int64

In [68]:
print(final_df['Isam'].dtypes)  # 应输出 float64
exchange_rates = {
    "CNY": 1.00,
    "USD": 7.20,
    "EUR": 7.80,
    "HKD": 0.92,
    "AUD": 4.80,
    "JPY": 0.05,
    "TWD": 0.23,
    "BRL": 1.45,
    "GBP": 8.80,
    "NZD": 4.40,
    "MYR": 1.55,
    "CAD": 5.20,
    "THB": 0.20,
    "SGD": 5.30,
    "VND": 0.0003,
    "IDR": 0.0005,
    "INR": 0.087,
    "DKK": 1.05,
    "ZAR": 0.39,
    "KRW": 0.0052,
    "AED": 1.96,
    "PLN": 1.80,
    "HUF": 0.020,
    "PKR": 0.025,
    "MXN": 0.42,
    "SEK": 0.66,
    "MOP": 0.89,
    "KWD": 23.50,
    "ILS": 1.90,
    "LAK": 0.00033,
    "CHF": 8.20,
    "CZK": 0.33,
    "EGP": 0.23,
    "RUB": 0.078,
    "QAR": 1.98,
    "OMR": 18.70,
    "MNT": 0.0021,
    "RON": 1.57,
    "NOK": 0.65,
    "BYR": 0.002,
    "TRY": 0.23,
    "UYU": 0.19,
    "LKR": 0.022,
    "UAH": 0.19,
}
final_df['Isam'] = pd.to_numeric(final_df['Isam'], errors='coerce').fillna(0)
final_df['Curtype'] = final_df['Curtype'].fillna('CNY')
final_df['transaction_CNY'] = final_df.apply(
        lambda row: row['Isam'] * exchange_rates.get(row['Curtype'], 1.0),
        axis=1
    )
final_df

float64

,Stkcd,Reptdt,Repat,Kind,Curtype,Isam,Content,transaction_CNY
0,600760,2017-12-31,5.0,拆入资金,CNY,40000000.0,拆入资金,40000000.0
1,600760,2017-12-31,5.0,拆入资金,CNY,100000000.0,拆入资金,100000000.0
2,600760,2017-12-31,5.0,拆出资金,CNY,20000000.0,拆出资金,20000000.0
3,600760,2017-12-31,5.0,拆出资金,CNY,50000000.0,拆出资金,50000000.0
4,600760,2017-12-31,5.0,拆出资金,CNY,50000000.0,拆出资金,50000000.0
...,...,...,...,...,...,...,...,...
651510,600760,2017-12-31,5.0,拆入资金,CNY,50000000.0,拆入资金,50000000.0
651511,600760,2017-12-31,5.0,拆入资金,CNY,46000000.0,拆入资金,46000000.0
651512,600760,2017-12-31,5.0,拆入资金,CNY,50000000.0,拆入资金,50000000.0
651513,600760,2017-12-31,5.0,拆入资金,CNY,62000000.0,拆入资金,62000000.0
651514,600760,2017-12-31,5.0,拆入资金,CNY,40000000.0,拆入资金,40000000.0

In [69]:

filtered_df = final_df[["Stkcd", "Reptdt", "transaction_CNY"]]

# 将 Reptdt 列只保留年份
filtered_df.loc[:, "Reptdt"] = pd.to_datetime(filtered_df["Reptdt"]).dt.year

# 输出筛选结果
print(filtered_df)

         Stkcd Reptdt  transaction_CNY
0       600760   2017       40000000.0
1       600760   2017      100000000.0
2       600760   2017       20000000.0
3       600760   2017       50000000.0
4       600760   2017       50000000.0
...        ...    ...              ...
651510  600760   2017       50000000.0
651511  600760   2017       46000000.0
651512  600760   2017       50000000.0
651513  600760   2017       62000000.0
651514  600760   2017       40000000.0

[651515 rows x 3 columns]

In [70]:
# 按公司和年份分组并求和
summed_df = filtered_df.groupby(['Stkcd', 'Reptdt'], as_index=False)['transaction_CNY'].sum()

# 输出结果
print(summed_df)

        Stkcd Reptdt  transaction_CNY
0      000002   2014     3.136624e+10
1      000002   2015     2.912840e+10
2      000002   2016     5.014138e+10
3      000002   2017     4.324287e+10
4      000002   2018     2.588006e+10
...       ...    ...              ...
28830  873679   2023     3.090000e+06
28831  873690   2023     2.221585e+07
28832  873693   2023     1.100000e+07
28833  873706   2023     4.000000e+08
28834  873833   2023     7.000000e+07

[28835 rows x 3 columns]

In [75]:
columns = {
        "Stkcd": "stock_id",
        "Accper": "year",
        "A001000000": "total_asset",
        
    }
df_asset = pd.read_csv(RAW / 'csmar' / '基本信息' / '资产负债表' / 'FS_Combas.csv',
                     usecols=columns.keys(), dtype={'Stkcd': str}).rename(columns=columns)
df_asset['year'] = pd.to_datetime(df_asset['year'], errors='coerce').dt.year

In [76]:
summed_df = summed_df.rename(columns={"Reptdt": "year",
                                       "Stkcd": "stock_id"})
df_merged = pd.merge(
    summed_df,
    df_asset,
    on=["stock_id", "year"],
    how="left"
)

In [77]:
df_merged["transaction_ratio"] = df_merged["transaction_CNY"] / df_merged["total_asset"]
df_merged

      stock_id  year  transaction_CNY   total_asset  transaction_ratio
0       000002  2014     3.136624e+10  5.084088e+11           0.061695
1       000002  2015     2.912840e+10  6.112956e+11           0.047650
2       000002  2016     5.014138e+10  8.306742e+11           0.060362
3       000002  2017     4.324287e+10  1.165347e+12           0.037107
4       000002  2018     2.588006e+10  1.528579e+12           0.016931
...        ...   ...              ...           ...                ...
28830   873679  2023     3.090000e+06           NaN                NaN
28831   873690  2023     2.221585e+07           NaN                NaN
28832   873693  2023     1.100000e+07           NaN                NaN
28833   873706  2023     4.000000e+08           NaN                NaN
28834   873833  2023     7.000000e+07           NaN                NaN

[28835 rows x 5 columns]

In [78]:
output_file = BLD / 'related_party_transactions.parquet'
df_merged.to_parquet(output_file, index=False)